version: '3'

services:
  
  minio0:
    image: minio/minio:RELEASE.2021-03-12T00-00-47Z
    env_file:
      - .docker-compose/.env
    command: ["server", "http://minio{0...3}/data{0...1}"]
    expose:
      - "9000"
    volumes:
      - minio0-data0:/data0
      - minio0-data1:/data1
    networks:
      - object-storage-network

  minio1:
    image: minio/minio:RELEASE.2021-03-12T00-00-47Z
    env_file:
      - .docker-compose/.env
    command: ["server", "http://minio{0...3}/data{0...1}"]
    expose:
      - "9000"
    volumes:
      - minio1-data0:/data0
      - minio1-data1:/data1
    networks:
      - object-storage-network

  minio2:
    image: minio/minio:RELEASE.2021-03-12T00-00-47Z
    env_file:
      - .docker-compose/.env
    command: ["server", "http://minio{0...3}/data{0...1}"]
    expose:
      - "9000"
    volumes:
      - minio2-data0:/data0
      - minio2-data1:/data1
    networks:
      - object-storage-network

  minio3:
    image: minio/minio:RELEASE.2021-03-12T00-00-47Z
    env_file:
      - .docker-compose/.env
    command: ["server", "http://minio{0...1}/data{0...1}"]
    expose:
      - "9000"
    volumes:
      - minio3-data0:/data0
      - minio3-data1:/data1
    networks:
      - object-storage-network

volumes:
  minio0-data0:
  minio0-data1:
  
  minio1-data0:
  minio1-data1:

  minio2-data0:
  minio2-data1:

  minio3-data0:
  minio3-data1:

networks:
    object-storage-network:
        driver: bridge
